version: '3.2'
services:
  mysql:
    restart: always
    image: mysql
    ports:
    - "3306:3306"
    environment: 
        MYSQL_DATABASE: 'IAM'
        MYSQL_USER: 'admin'
        MYSQL_PASSWORD: 'iam123'
        MYSQL_ROOT_PASSWORD: 'iam123'
        DEMO_MODE: 'DEV'
    expose:
        - '3306'